# Generated by Django 2.0.13 on 2019-12-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='agenda_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
