# Generated by Django 2.0.13 on 2019-12-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_reply_agenda_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='agenda_id',
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='agenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.Agenda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_num',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
