# Generated by Django 2.0.13 on 2019-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191217_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_num',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='agenda_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
