# Generated by Django 2.0.13 on 2019-12-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20191217_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='agenda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='community.Agenda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='agenda_num',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
