# Generated by Django 3.0.1 on 2020-01-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20191217_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='agenda_nickname',
            field=models.CharField(default='Anon', max_length=100),
        ),
    ]
